name: Build 🏗️

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node: ["18.x", "20.x", "21.x"]
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.platform }}

    # Build | ubuntu-latest-node-18.x
    name: "Build | ${{ matrix.platform }}-node-${{ matrix.node }}"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: NPM Install
        run: |
          npm install

      - name: Build
        run: |
          npm run build

      - name: Lint
        run: |
          npm run lint
